version: '3.8'
services:
  web:
    build: ./producer
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: playful-rabbit
    ports:
      - 15672:15672
      - 5672:5672