version: '3.8'
services:
  web:
    build: ./producer
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    command: flask run -h 0.0.0.0
    restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
